from __future__ import annotations

from typing import Any, Protocol


class VehicleStatePort(Protocol):
    def get_active_source(self) -> str: ...
    def get_latest_drone_state(self) -> Any: ...
    def get_latest_gimbal_state(self) -> Any: ...
    def get_link_status(self) -> Any: ...


class VehicleCommandPort(Protocol):
    def clear_continuous_commands(self) -> None: ...
    def clear_pending_local_position_actions(self) -> None: ...
    def local_position(self, x: float, y: float, z: float, *, frame: int,
                       yaw: float | None = None, priority: int = 4) -> Any: ...
    def stop_body_velocity_and_clear(self) -> None: ...
    def stop_body_velocity(self) -> None: ...
    def hold_current_local_position(self) -> Any: ...
